name: Auto-release DTO-lib

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - id: rp
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: release-please-config.json

      - name: Publish to GitHub Packages
        if: steps.rp.outputs.release_created == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}
      - if: steps.rp.outputs.release_created == 'true'
        run: mvn -B
