name: Auto-release DTO-lib

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - id: rp
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Set up JDK 21
        if: steps.rp.outputs.release_created == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Deploy to GitHub Packages
        if: steps.rp.outputs.release_created == 'true'
        run: mvn -B deploy -P release -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}