name: Auto-install & Deploy DTO-lib

on:
  push:
    branches: [master]

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Build and install
        run: mvn clean install -B
        working-directory: ./lna-session-dto

      - name: Deploy to GitHub Packages
        run: mvn deploy -B -DskipTests
        working-directory: ./lna-session-dto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}