name: Test, Install and Auto-release lna-session-dto

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Test and Install
        run: mvn -B clean install
        working-directory: ./lna-session-dto

      - id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: release-please-config.json

      - name: Publish to GitHub Packages
        if: steps.release-please.outputs.release_created == 'true'
        run: mvn -B deploy -DskipTests
        working-directory: ./lna-session-dto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}